version: '3'

services:
  # A container that runs elasticsearch. The upstream image has a volume defined,
  # so indexes persist.
  es:
    build: ./tooling/docker/es
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - dxr

  # An interactive container for experimentation and debugging
  dev:
    build: ./
    ports:
      - "8010:8000"
    networks:
      - dxr
    volumes:
      - /home/dylan/projects/dxr-code:/code
      # - dxr_code:/code
      - dxr_venv:/venv

networks:
  dxr:

volumes:
  dxr_code:
  dxr_venv:

